### ISSUE TITLE
Kernel panic - not syncing: Fatal exception in interrupt

### ISSUE THREAD

**Issue by jbsky** [Chadster766/McDebian#5]
For WRT1900AC v1 - kernel 4.3 - jessie.  I follow your instruction here: http://www.snbforums.com/threads/linksys-wrt1900-1200-router-series-debian-os-implementation.28394/. I use your source to mwlwifi and I apply this patch http://pastebin.com/Vp19wxR4.
Reproductible when I upload to McDebian a huge file via smb.

[kernl.txt](https://github.com/Chadster766/McDebian/files/118841/kernl.txt)

**Comment by Chadster766** [comment]
Your firmware and rootfs isn't McDebian. 

You did a great job of creating your own custom kernel firmware and rootfs but I can't support it because it's too far removed from the current McDebian firmware and rootfs.

I recommend you backup your current rootfs USB key and custom firmware. Then follow the instructions below to use the current version of McDebian firmware and rootfs with latest rootfs updates.

https://github.com/Chadster766/McDebian/wiki/2.-Firmware-Uploading
https://github.com/Chadster766/McDebian/wiki/3.-Make-Root-File-System
https://github.com/Chadster766/McDebian/wiki/X.-McDebian-rootfs-Updates

The only thing missing in the current version of McDebian is the wireless driver ampdu fix that is in patch you mentioned.

To install the ampdu fix into McDebian rootfs V1.0.0 you need to apply the testing rootfs module update below which you apply the same as any other McDebian rootfs update:

http://www.protechs-online.com/downloads/McDebian/rootfs-updates/mcdebian-module-update-testing.gz

It would be great if you had to two USB Keys. Then you could testing with McDebian firmware and rootfs for comparison with your custom firmware and rootfs. This would greatly help McDebian development as well.

Let me know if you would like to be listed as a member of the development team on the Wiki home page.

**Comment by jbsky** [comment]
I follow your instruction. With the McDebian firmware and rootfs, when a huge was upload into smb server, kernel crash.
Before module update
[kernl_2.txt](https://github.com/Chadster766/McDebian/files/119810/kernl_2.txt)
After module update.
[kernl_3.txt](https://github.com/Chadster766/McDebian/files/119809/kernl_3.txt)

If not, perf is very good! Thx for your patch. 

Add me of the dev'team.

**Comment by Chadster766** [comment]
Ok great :smile: I will add you to the Dev Team on the home wiki page. I would like to look into this in more detail.

1. What is the file size used in the test?
2. How did you install smb in the McDebian system?
3. How was the files transfer done? (Windows, Mac, etc...)
4. Is the smb share on a drive attached to the WRT1900AC or on a computer on the LAN?

**Comment by jbsky** [comment]
1/ file > 300MByte.
2/ via ssh: apt-get install samba.

I add one user with password to match windows's user.
3/ The file is copied from windows 7 to smb server.
4/ Smb share is directly attached to the WRT1900AC, on the usb key, 16GB. (/home/%U)

I'll try with a new kernel 4.4.1.

**Comment by Chadster766** [comment]
You are right. A SMB wireless file transfer of > 500mb to a USB Drive attached to the router will fail.

Samba is using up all the memory and leaving nothing left for the system. I think we need to use cgroups or another process to limit smbd service memory usage.

**Comment by jbsky** [comment]
So, in a systemd environnement, service belong to system.slice cgroup. There is possible to set a memory limit with the following command :
`systemctl set-property smbd MemoryLimit=192M`
To check system.slice:
`systemd-cgtop`
But, the perf is not really good,13Mbytes/s over smb transfert with a huge file. I think, 
it is possible to do better.

**Comment by Chadster766** [comment]
Great :smile: 

Try giving smbd 400M instead of 64M.

**Comment by jbsky** [comment]
Wrt1900ac has 256MBytes... lol, The max is 192Mbytes with a big risk of crash. 64MB is reasonable, 128 is also good if no other server is running like LAMP.

**Comment by Chadster766** [comment]
Sorry I was thinking of the WRT1900AC V2\ACS and WRT1200.

I think the minimum would be 128M. How does smbd perform with that amount of ram?

**Comment by jbsky** [comment]
Nothing changes. 13Mbytes/s over smb transfert with a huge file.

**Comment by Chadster766** [comment]
What is the maximum transfer rate the usb key supports?

**Comment by jbsky** [comment]
I use only kingston G4 datatraveler. http://usb.userbenchmark.com/Kingston-DataTraveler-G4-USB-30-32GB/Rating/1996
The USB key is plug into usb3 port :
`root@WRT1900AC:~# lsusb -t`
`/:  Bus 03.Port 1: Dev 1, Class=root_hub, Driver=orion-ehci/1p, 480M`
`/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/2p, 5000M`
`    |__ Port 2: Dev 2, If 0, Class=Mass Storage, Driver=usb-storage, 5000M`
`/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/2p, 480M`

**Comment by Chadster766** [comment]
I just had two Kingston DataTraveler 100 G3 fail with bad blocks. I think it's due to that **_some _**Kingston USB keys don't have built in wear leveling. AFAIK all Sandisk and Corsair USB keys have build in wear leveling.

I've purchase some for testing.

Not that this is the cause of the performance issue. If you had bad blocks on the usb key they would show as journalctl entries.

**Comment by Chadster766** [comment]
In that link for the USB key you are using a user posted:

Rubbish USB stick. Write only 13MB/s

**Comment by jbsky** [comment]
What do you think about Corsair Flash Voyager GT USB 3.0?

**Comment by Chadster766** [comment]
It's a fast one with wear leveling. You should get 70-80mb read\write.

**Comment by jbsky** [comment]
You are right. 
I plug a harddisk into usb 2. Write speed up to 24MB/s. Kingston is a rubbish USB stick.

**Comment by Chadster766** [comment]
Thanks so much for finding the below solution to this issue :smiley: 

Set a memory limit for smbd with the following command :
`systemctl set-property smbd MemoryLimit=64M`
 
To check system.slice:
`systemd-cgtop`
