### ISSUE TITLE
Enable 40MHz channels in hostapd Wifi N 2.4 Ghz

### ISSUE THREAD

**Issue by Lovator** [Chadster766/McDebian#54]
Good afternoon, how to enable the mode of operation HT40 ?

changed the /etc/hostapd/wlp2s0.conf parameter
ht_capab = [HT40 +] [SHORT-GI-40] [DSSS_CCK-40]
ht_capab = [HT40 -] [SHORT-GI-40] [DSSS_CCK-40]
but the channel width of 40 Mhz never turned on.

**Comment by Chadster766** [comment]
interface=wlp2s0
bridge=br0
driver=nl80211
ctrl_interface=/var/run/hostapd
ssid=McWifi-24
ignore_broadcast_ssid=0
hw_mode=g
channel=11
auth_algs=1
wmm_enabled=1
ieee80211n=1
ht_capab=[LDPC][SHORT-GI-20][SHORT-GI-40]
ieee80211ac=0

**Comment by Chadster766** [comment]
AFAIK it should work with the McDebian default config but that the 40mhz co-existence rule is enforced by the wireless driver.

I have an AP broadcasting on 40mhz so I will have to power it off for testing later this evening.

This can be hacked with at hostapd patch file available from many sources but I don't plan to implement it since 2.4Ghz typically runs best at 20mhz for most devices anyway.

**Comment by Lovator** [comment]
I correctly understood that in your mcdebian there is no support for 40 Mhz for Wifi N ?

**Comment by Chadster766** [comment]
No 2.4ghz 40mhz is supported but so is the FCC 40Mhz co-existence rule.

**Comment by Chadster766** [comment]
I did some testing for you.

To get 40Mhz enabled on 2.4Ghz you only need to add [HT40+] or [HT40-] (no space between the HT40 and plus\minux) to the default McDebian wireless config.

I discovered something new that if you set 2.4Ghz channel to 11 and use [HT40+] hostapd will fail to start. I believe this is because you need at 4 channels above 11 when using [HT40+] which don't exist. To resolve this issue I changed it to [HT40-]. This cause hostapt to use channels 11+7 hence the "-" in [HT40-].

I tested with channel 1 and [HT40+] which caused hostapt to use channels 1+5.

To get may AP which was using 40 Mhz channel 1+5 to work with my WRT I set the WRT to [HT40-] 40Mhz channels 11+7. This made sure the FCC 40Mhz rule did come into effect and drop the WRT down to 20Mhz.
